nushell/vscode-nushell-lang

- .gitattributes
- .gitignore
- .vscode/launch.json
- .vscodeignore
- CHANGELOG.md
- README.md
- language-configuration.json
- nushell-code-colors.json
- nushell.theme-minimal.json
- nushell.theme.json
- package.json
- sample.nu
- syntaxes/nushell.tmLanguage.json
- syntaxes/nushell.tmLanguage.json.bak
- used_keywords.jsonc
still lots of work to do but good enough to add here i think
> working-ish

- language-configuration.json
> update comments to # vs /

- nushell.theme-minimal.json
- package.json
- syntaxes/nushell.tmLanguage.json
added all keywords and sub commands
added + % / *
fixed [$var
added keyword.other for sub commands
fixed foo-bar
> bunch of fixes

- .github/workflows/package.yml
- nushell.theme-minimal.json
- package.json
- syntaxes/nushell.tmLanguage.json
trying to fix `my-ls` problem. current "fix" creates a situation where `$(ansi blah)` is not highlighted right but `$( ansi blah)` is.
> add ci + wip regexes

- README.md
~~WIP improvements to the readme (on mobile, will continue later in desktop). Any early feedback or suggestions are welcome though.~~
Update: Now ready for review. Changes in this PR:
- Edit main title to be more informative
- Unwrap some lines, since wrapping was inconsistent
- Add link to page explaining VSCode extensions
- Add alt text to the screenshots
- Add missing word ("engine")
- Format commands as code
- Harmonize verb tense in step-by-step instructions
- Format keyboard shortcuts with the `<kbd>` element
- A few additional minor tweaks
> README: various improvements 

- CHANGELOG.md
- README.md
made screenshots urls so they'll show up in vscode 
tweaked changelog
> minor updates to docs

- .github/workflows/release.yml
> update info-from-package-json to 1.1.0

- example.nu
- generate-patterns.nu
- syntaxes/nushell.tmLanguage.json
Commands with hyphens are now sorted before commands without which fixes coloring of commands such as group-by
Commands with single subcommands (each while, encode base64 etc) now have coloring generated
> Updated syntax + fixed generation script

- src/extension.ts
> fix: ⚡️ add path for arm brew

- CHANGELOG.md
- example.nu
- generate-example.nu
- generate-patterns.nu
- nushell.theme-minimal-dark.json
- nushell.theme-minimal-light.json
- package.json
- syntaxes/nushell.tmLanguage.json
- 0.8.0
- added path for arm brew @melMass
- update readme screenshots
- add the old dark and light themes to repo for anyone who wants to use them
- update example.nu for testing
- update generate-example.nu to include all samples
- update generate-patterns.nu to support the new language features
- update language syntax to support new nushell 0.72 features (break, continue, return, loop, try, catch, mut, while, err>, out>, err+out>, out+err>)
> updates for nushell 0.72

- syntaxes/nushell.tmLanguage.json
This PR should correct #71 after the next extension release.
> add `and` and `or` so they highlight properly

- CHANGELOG.md
- package.json
Just make some changes so the next release won't be a preview. Doing it now so I don't forget. :)
> next release won't be a preview

- README.md
> add some badges to the readme

- package.json
- server/src/server.ts
This change adds a new extension setting that allows additional folders to be included for searching when using the hover and other features.
> add include dirs setting to extension

- .vscode/launch.json
Having launch call `watch` instead of `compile` was causing issues for me, so I switched it to just build.
> Have launch build instead of watch

- example.nu
- generate-example.nu
This PR updates the example generation script and the examples that it generates. This is helpful for looking at a broad range of commands to check syntax highlighting and looking for ide errors.
> update example generation script and examples

- syntaxes/nushell.tmLanguage.json
Update the syntax regexes for the latest nushell.
> update syntax for 0.79.0

- CHANGELOG.md
- package.json
update the version and changelog in preparation for a 1.5.1 release
> update version and changelog

- snippets/nushell.json
Snippets for creating completions.
> feat(snippets): completions

- snippets/nushell.json
Snippets to quickly create docs for functions. Ideas for warnings and infos came after reading [this](https://github.com/orgs/community/discussions/16925) post.
> feat(snippets): markdown doc sections

- snippets/nushell.json
https://github.com/nushell/vscode-nushell-lang/pull/127#issuecomment-1549939091
Based on ide.rs exploration.
> feat(snippets): use H3 headers

- syntaxes/nushell.tmLanguage.json
Improve the color of types in function parameters and in->out
Before
After
> Improve type parsing in function def
