nushell/vscode-nushell-lang

- .github/workflows/release.yml
This adds a release pipeline however it's hard coded to 0.0.5. We need to figure out how to dynamically change the version number for uploading the release.
The release is supposed to run automagically when a release is tagged with `v*`
> add release pipeline

- CHANGELOG.md
- package.json
- syntaxes/nushell.tmLanguage.json
- 0.4.1
- syntax changed to allow optional `$` in variable name
- syntax changed to allow space after custom command parameters
- added `in` to go with `for`
> updated regex to match new syntax

- src/extension.ts
The path lookup doesn't respect PATHEXT so `nu` doesn't find `nu.exe`
> Catch the install to cargo/bin on Windows

- snippets/nushell.json
The alias snippet said “aliase” instead of “alias”
> Fix typo in Snippet

- src/extension.ts
@fdncred Following issue #81, includes a trivial insert to check for `usr/bin/nu` for installed binary using package managers on Linux
> modified extension.ts to include standard dir for binary files on linux

- CHANGELOG.md
- syntaxes/nushell.tmLanguage.json
Fixes a small bug where `use` was highlighted incorrectly after #79. Thanks @glcraft for your help!
> fix `use` when it's used in variable name

- server/src/server.ts
Once https://github.com/nushell/nushell/pull/8857 lands, this will use `-I` to pass along the project directory to Nushell so it can find imported files.
> Add support for -I call to nushell

- .vscodeignore
This reverts some changes to the vscode that I just found out broke the extension.
> revert vscodeignore changes

- server/src/server.ts
This PR changes the include dir separator from a semicolon to a colon. It seems that nushell has difficulty parsing strings with semicolons so this is just an easier way to do it.
> change include dir separator from semicolon to colon

- server/src/server.ts
This PR limits the amount of errors returned by the ide-check parameter on nushell
Configured amount of errors
Lots of errors but only showing 5, the configured amount of errors
> limit the amount of errors returned by ide-check

- .vscode/launch.json
This PR removes the `outFiles` node in the launch configuration because it was preventing me from doing client side logging.
> update vscode launch json so we can see debug messages from client

- server/src/server.ts
This PR adds a throttle to how often the document validation happens. 
I discovered we needed something like this while I was doing some script programming and watching the logs. I was adding comments to variables and custom commands when I noticed that on every single character that I typed, we called out to nushell to revalidate the document.
I found the main throttle function in jakt's extension but adjusted the timeout to 1500. I'm not sure 1500 is correct. The idea is only to update after a certain duration versus every character. We'll have to tune this over time.
> add a throttle timeout so that we don't update to frequently

- syntaxes/nushell.tmLanguage.json
I changed number parsing to make underscore separator works. 
If the parsing is wrong, the number is not parsed as a number and by default, the extension goes for a bare string (as you can see on the screen).
closes #76
> Add underscore separator in numbers

- CHANGELOG.md
- language-configuration.json
This PR adds folding regions so that you can fold your code as you want it.
By adding `# region:` and `# endregion` around the code you want to fold, you can go from this.
To this.
> add folding regions

- server/src/server.ts
This changes how the include paths are joined together so that it uses a character that will work across platforms. `;` didn't work on Mac/Linux. `:` didn't work in Windows. So, the `record separator` should work, which is `\x1e`.
This goes hand-in-hand with https://github.com/nushell/nushell/pull/8961
> change the `:` separator to a record separator `\x1e`

- syntaxes/nushell.tmLanguage.json
From https://github.com/nushell/vscode-nushell-lang/issues/139
* floating point seconds can have one or more digits (instead of up to 3)
* datetime rule is prioritized over numbers rule, so that the year is not parsed as number first instead of a full date.
> Fix datetime parsing

- server/package-lock.json
- server/package.json
- server/src/server.ts
> fix go to definition on windows

- package-lock.json
- server/src/server.ts
At least fixes the error in #134 , but not the actual reason why nu returns `"file" : "source"` sometimes.
> Don't try to read if file doesn't exist

- package.json
Allow for detection of scripts without extension by using the first line detection, aka shebang.
Shamelessly copied from the python extension.
https://github.com/microsoft/vscode/blob/3519b130fbbd41281980d726dae3ca964305b329/extensions/python/package.json#L34
> fix shebang/firstLine detection

- client/package.json
- client/src/extension.ts
I tried out the vscode extension today and it gave error. so I looked at the code and found out the `nu` installation detection logic is manually searching through a hard coded list of directores, but my setup happens to be not in any of the presumed locations. so I modified the code to use `which` to search in `${env:PATH}`, plus these additional locations, and also simplfied the code a little bit during the process.
also, I don't like the generic "terminal" icon, and I find there's already a svg icon file in the assets folder so I just point the terminal profile icon path to that svg file.
> use `which` to search `nu` location, add icon too.

- snippets/nushell.json
- snippets for comparisons in `if` and `while`
- snippets for iterating over ranges and files for `for`
- simplify snippet names for builtins
- remove snippets for list, table and range creations as they are simple constructs to type
- use `${<number>:command ...}` instead of `${<number>:block}` and `${<number>:closure}`
> More conditional and loop snippets

- syntaxes/nushell.tmLanguage.json
A little fix which fix color of "export module"
Before:
After:
> Syntax highlight: add "export" to "module"

- syntaxes/nushell.tmLanguage.json
* Improvement on closure parameters parsing (`{|...| }`)
* Improvement on record entries (fields name) parsing (`field:`)
**Known issue :**
There are issues in interpolated strings if there is a quote following by a colon.
> Textmate: improvement on record entries and closure

- syntaxes/nushell.tmLanguage.json
Fixes #173.
Generated tokens for:
```nushell
def cmd [--flag (-f) ...rest] {
[ ...$rest ]
{ ...$rest }
all --flag -f ...$rest
}
cmd --flag -f ...$rest
^cmd --flag -f ...$rest
```
- `def cmd [`
- `...`
1. `keyword.control.nushell`
2. `meta.function.parameters.nushell`
3. `source.nushell`
- `rest`
1. `variable.parameter.nushell`
2. `meta.function.parameters.nushell`
3. `source.nushell`
- `] {`
- `[`
- `...`
1. `keyword.control.nushell`
2. `meta.table.nushell`
3. `meta.function.body.nushell`
4. `source.nushell`
- `$rest`
1. `variable.other.nushell`
2. `meta.table.nushell`
3. `meta.function.body.nushell`
4. `source.nushell`
- `]`
- `{`
- `...`
1. `keyword.control.nushell`
2. `meta.expression.braced.nushell`
3. `meta.function.body.nushell`
4. `source.nushell`
- `$rest`
1. …
> Add spread to syntax highlighting

- client/src/extension.ts
- server/src/server.ts
Hi, I wandered around for a bit and found out that when the server returns a hover, [you have to inform](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#markupContentInnerDefinition) the client which type of `plaintext | markdown` [you are returning](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#markupContent).
So, instead of
```typescript
const contents = {
value: obj.hover, // actual hover string
language: "nushell",
};
```
it should be
```typescript
const contents = {
value: obj.hover, // actual hover string
kind: "markdown"
};
```
(note that both key and value changed)
and you get the result 😄 
By removing the `language: nushell` key, it defeats me how vscode knows that the code block (`\``) …
> :bug: fix markdown formatting for hover lsp

- .github/workflows/release.yml
- CHANGELOG.md
- package.json
update changelog and package.json version.
rejigger release ci to publish release assets first, then marketplace (commented out for now because it doesn't work), then openvsx.
> update version and changelog

- language-configuration.json
This removes `/` and `\` from the `wordPattern` value in the `language-configuration.json`, which fixes #185, allowing path completion to work properly.
https://code.visualstudio.com/api/language-extensions/language-configuration-guide#word-pattern
> `wordPattern` defines what's considered as a word in the programming language. Code suggestion features will use this setting to determine word boundaries if `wordPattern` is set.
I'm not entirely sure this is the best possible fix, but everything I tested seems to work the way I expected and I can auto-complete paths now. For example, I tried creating a variable with a slash in the name, but it still doesn't treat that as a valid variable name.
Two thoughts according to my limited understanding of how this works:
1. I see that the current …
> Remove `/` and `\` from wordPattern

- README.md
- package.json
- syntaxes/codeblock.json
Adds syntax highlighting for nushell code blocks when editing markdown files inside VS code
The code is very inspired from [this repo](https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example).
⚠️ The syntax highlighting still is **not available** when opening the Preview of the md files in VS code. VS code uses something else (highlight.js) so that will be done and somewhere else I guess.
1. Clone the branch
2. Start debugging (F5) in VS Code
3. Open a md files, create a ``nushell`` code block and start typing nushell code
> Feat: syntax highlighting in markdown code blocks

- client/package-lock.json
- package-lock.json
- package.json
When running ``npm install`` or ``npm audit``, we get
``Found three vulnerabilities (1 low, 1 medium, 1 high)``
So I tried to fix it: I ran ``npm audit fix`` from the package's root, from client/ and server/. npm 10.9.2.
**I'm not used to working with npm** though, so let me know if this was the right way! 
Now when you ``npm install``, you get ``0 vulnerabilities``.
I just launched the extension with VS code debugging, it works. But I couldn't run the test, I'll open another PR for that
> fix: vulnerabilities detected by npm audit

- language-configuration.json
- syntaxes/nushell.tmLanguage.json
This pull request adds syntax highlighting for raw strings (#196) and autoClosingPairs.
- Since autoClosingPairs does not seem to support regex open/close, I have had to repeat a couple of possible raw string pairs. One could add more...
- The current highlight color chosen (for `r`, `#` and the string itself) is of course opinionated. I just choose that which I found easiest to implement.
- I have not added the condition `"notIn": ["comment"]`, because while typing a raw string, one enters a comment `r#`, and the `notIn` would therefore always fail. This could be changed however, depending on question 3. below.
1. Some raw string examples should probably be included in `example.nu`, however that file is generated and so  I do not know how the example strings should be added.
2. …
> Support raw strings

- language-configuration.json
Removes the autoClosingPair `/**` `*/` which means nothing in particular to Nushell.
> Remove irrelevant autoClosingPair /**

- syntaxes/nushell.tmLanguage.json
- Added `µs` as a valid unit.
- Added the new operators `like` and `not-like`.
- Disallowed semicolon in bare strings (this should also fix #190)
- Allowed `#` in bare strings (except for the first character, since then it is a comment and not a bare string).
- Prioritized raw string highlighting over commands and bare strings (in e.g. `r'#str#'`, `r` should not be highlighted as a command).
- Technically, commas should also be allowed in bare strings. However, commas can only be in some bare strings, since if the bare string is inside a list, then commas should not be recognized as part of the bare string: `[bare,strings]`). Hence, I have left commas disallowed as they were before.
- The new operators `like` and `not-like` are missing from the [Nushelll operators …
> Improve highlighting of bare and raw strings, and add missing unit & operators

- syntaxes/nushell.tmLanguage.json
Aside from adding the two missing operators, I think the regex looks slightly better now by using extra groups to avoid repeating e.g. `not-`?
- It might be better to automatically generate the list of binary operators, using the output of `help operators | select operator`, but meh.
- Another currently not highlighted operator is the (unary) [optional operator](https://www.nushell.sh/book/types_of_data.html#nothing-null) that can only be used on cell-paths. I might see if I can add it, but that will probably require improved syntax highlighting of various valid cell-paths.
> Add operators 'has' & 'has-not', and shorten operators-word regex

- syntaxes/nushell.tmLanguage.json
- Highlighting for numbers with exponential, e.g. `3E4` or `4e-1`.
- Highlighting for the numbers `infinity` and `NaN`.
- Octal and binary constants, e.g. `0b01` and `0o37`.
- Numbers with possibly absurd but valid usages of underscores. All of these are valid numbers in Nushell:
```nushell
+___3.____
____NAN____
_____.__4__
___-___Inf
___0__x___3___44___44____
_+_____3___e___0___
_00_0_._3___e___00__03__
```
In other words, underscores can go anywhere in numeric literals. I have however not supported valid numbers such as ```_-_inf____in_ity```, since that would make the regex much less readable than it already is, and I think that anyone who uses that kind of constant does not deserve pretty syntax highlighting for it >:(.
- I have used possessive quantifiers everywhere as to avoid …
> Support floats, binary & octal literals (with underscores)

- syntaxes/nushell.tmLanguage.json
This updates the `def` syntax so that it supports these:
- def bar [...args] {}
- def bar --wrapped --env [...args] {}
- def bar --env [...args] {}
- def bar --wrapped [...args] {}
- def --wrapped --env bar [...args] {}
- def --env bar [...args] {}
- def --wrapped bar [...args] {}
- def --wrapped bar --env [...args] {}
The lsp still doesn't like it but that's a different repo.
closes #221
> update `def` syntax
